const planetNames = [
    'Jord',
    'Moll Primus',
    'Darien',
    'Muaat',
    'Nestphar',
    '[0.0.0]',
    'Winnu',
    'Mordai II',
    'Maaluuk',
    'Druaa',
    'Wren Terra',
    'Arc Prime',
    'Lisis II',
    'Ragh',
    'Jol',
    'Nar',
    "Tren'lak",
    'Quinarra',
    'Archon Ren',
    'Archon Tau',
    'Retillion',
    'Shalloq',
    'Arretze',
    'Hercant',
    'Kamdorn',
    'Mecatol Rex',
    'Wellon',
    'Vefut II',
    'Thibah',
    "Tar'mann",
    'Saudor',
    'Mehar Xull',
    'Quann',
    'Lodor',
    'New Albion',
    'Starpoint',
    "Tequ'ran",
    'Torkan',
    "Qucen'n",
    'Rarron',
    'Mellon',
    'Zohbat',
    'Lazar',
    'Sakulag',
    'Dal Bootha',
    'Xxehan',
    'Corneeq',
    'Resculon',
    'Centauri',
    'Gral',
    'Bereg',
    'Lirta IV',
    'Arnor',
    'Lor',
    'Arinam',
    'Meer',
    'Abyz',
    'Fria',
    'Creuss',
    'Ixth',
    'Arcturus',
    'Acheron',
    'Elysium',
    'The Dark',
    'Naazir',
    'Rohka',
    'Ylir',
    'Valk',
    'Avar',
    'Archon Vail',
    'Perimeter',
    'Ang',
    'Sem-lore',
    'Vorhal',
    'Atlas',
    'Primor',
    "Hope's End",
    'Cormund',
    'Everra',
    'Accoen',
    'Jeol Ir',
    'Kraag',
    'Siig',
    "Ba'kal",
    'Alio Prima',
    'Lisis',
    'Velnor',
    'Cealdri',
    'Xanhact',
    'Vega Major',
    'Vega Minor',
    'Abaddon',
    'Loki',
    'Ashtroth',
    'Rigel II',
    'Rigel III',
    'Rigel I',
    'Mallice',
    'Mirage',
    'Custodia Vigilia',
    'Silence',
    'Echo',
    'Tarrock',
    'Prism',
    'Troac',
    'Etir V',
    'Vioss',
    'Fakrenn',
    'San-vit',
    'Lodran',
    'Dorvok',
    'Derbrae',
    'Moln',
    'Rysaa',
    'Salin',
    'Gwiyun',
    'Inan',
    'Swog',
    'Detic',
    'Lliot',
    'Qaak',
    'Larred',
    'Nairb',
    'Sierpen',
    'Mandle',
    'Regnem',
    'Domna',
    'Rhune',
    'Kroll',
    'Cyrra',
    'Idyn',
    'Pax',
    'Kyr',
    'Vess',
    'Ogdun',
    'Brthkul',
    'Drah',
    'Trykk',
    'Vadarian',
    'Norvus',
    'Biaheo',
    'Empero',
    'Demis',
    'Chrion',
    'Axis',
    'Sanctuary',
    'Shi-Halaum',
    'Discordia',
    'Cymiae',
    'Prind',
    'Gen',
    'Zelian',
    'Vaylar',
    'Delmor',
    'Kyd',
    'Abyssus',
    'Louk',
    'Auldane',
    'Ellas',
    'Aldra',
    'Beata',
    'Bohl-Dhur',
    'Susuros',
    'Poh',
    'Orad',
    'Kjalengard',
    'Hulgade',
    'Benc',
    'Hau',
    'Zarr',
    'Nokk',
    'Last Stop',
    "Aysis' Rest",
    'Solitude',
    'Avicenna',
    'Alesna',
    'Azle',
    'Arche',
    'Gghurn Theta',
    'Ekko',
    'Edyn',
    'Okke',
    'Ghoti',
] as const;

type PlanetName = (typeof planetNames)[number];

type PlanetTrait = 'cultural' | 'hazardous' | 'industrial';

type ResourcesAndInfluence = {
    resources: number;
    influence: number;
};

type PlanetMeta = ResourcesAndInfluence & {
    trait?: PlanetTrait;
};

const planets: Record<PlanetName, PlanetMeta> = {
    Jord: {
        resources: 4,
        influence: 2,
    },
    'Moll Primus': {
        resources: 4,
        influence: 1,
    },
    Darien: {
        resources: 4,
        influence: 4,
    },
    Muaat: {
        resources: 4,
        influence: 1,
    },
    Nestphar: {
        resources: 3,
        influence: 2,
    },
    '[0.0.0]': {
        resources: 5,
        influence: 0,
    },
    Winnu: {
        resources: 3,
        influence: 4,
    },
    'Mordai II': {
        resources: 4,
        influence: 0,
    },
    Maaluuk: {
        resources: 0,
        influence: 2,
    },
    Druaa: {
        resources: 3,
        influence: 1,
    },
    'Arc Prime': {
        resources: 4,
        influence: 0,
    },
    'Wren Terra': {
        resources: 2,
        influence: 1,
    },
    'Lisis II': {
        resources: 1,
        influence: 0,
    },
    Ragh: {
        resources: 2,
        influence: 1,
    },
    Jol: {
        resources: 1,
        influence: 2,
    },
    Nar: {
        resources: 2,
        influence: 3,
    },
    Quinarra: {
        resources: 3,
        influence: 1,
    },
    "Tren'lak": {
        resources: 1,
        influence: 0,
    },
    'Archon Ren': {
        resources: 2,
        influence: 3,
    },
    'Archon Tau': {
        resources: 1,
        influence: 1,
    },
    Retillion: {
        resources: 2,
        influence: 3,
    },
    Shalloq: {
        resources: 1,
        influence: 2,
    },
    Arretze: {
        resources: 2,
        influence: 0,
    },
    Kamdorn: {
        resources: 2,
        influence: 0,
    },
    Hercant: {
        resources: 1,
        influence: 1,
    },
    'Mecatol Rex': {
        resources: 1,
        influence: 6,
    },
    Wellon: {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    'Vefut II': {
        resources: 2,
        influence: 2,
        trait: 'hazardous',
    },
    Thibah: {
        resources: 1,
        influence: 1,
        trait: 'industrial',
    },
    "Tar'mann": {
        resources: 1,
        influence: 1,
        trait: 'industrial',
    },
    Saudor: {
        resources: 2,
        influence: 2,
        trait: 'industrial',
    },
    'Mehar Xull': {
        resources: 1,
        influence: 3,
        trait: 'hazardous',
    },
    Quann: {
        resources: 2,
        influence: 1,
        trait: 'cultural',
    },
    Lodor: {
        resources: 3,
        influence: 1,
        trait: 'cultural',
    },
    'New Albion': {
        resources: 1,
        influence: 1,
        trait: 'industrial',
    },
    Starpoint: {
        resources: 3,
        influence: 1,
        trait: 'hazardous',
    },
    "Tequ'ran": {
        resources: 2,
        influence: 0,
        trait: 'hazardous',
    },
    Torkan: {
        resources: 0,
        influence: 3,
        trait: 'cultural',
    },
    "Qucen'n": {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    Rarron: {
        resources: 0,
        influence: 3,
        trait: 'cultural',
    },
    Mellon: {
        resources: 0,
        influence: 2,
        trait: 'cultural',
    },
    Zohbat: {
        resources: 3,
        influence: 1,
        trait: 'hazardous',
    },
    Lazar: {
        resources: 1,
        influence: 0,
        trait: 'industrial',
    },
    Sakulag: {
        resources: 2,
        influence: 1,
        trait: 'hazardous',
    },
    'Dal Bootha': {
        resources: 0,
        influence: 2,
        trait: 'cultural',
    },
    Xxehan: {
        resources: 1,
        influence: 1,
        trait: 'cultural',
    },
    Corneeq: {
        resources: 1,
        influence: 2,
        trait: 'cultural',
    },
    Resculon: {
        resources: 2,
        influence: 0,
        trait: 'cultural',
    },
    Centauri: {
        resources: 1,
        influence: 3,
        trait: 'cultural',
    },
    Gral: {
        resources: 1,
        influence: 1,
        trait: 'industrial',
    },
    Bereg: {
        resources: 3,
        influence: 1,
        trait: 'hazardous',
    },
    'Lirta IV': {
        resources: 2,
        influence: 3,
        trait: 'hazardous',
    },
    Arnor: {
        resources: 2,
        influence: 1,
        trait: 'industrial',
    },
    Lor: {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    Arinam: {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    Meer: {
        resources: 0,
        influence: 4,
        trait: 'hazardous',
    },
    Abyz: {
        resources: 3,
        influence: 0,
        trait: 'hazardous',
    },
    Fria: {
        resources: 2,
        influence: 0,
        trait: 'hazardous',
    },
    Creuss: {
        resources: 4,
        influence: 2,
    },
    Ixth: {
        resources: 3,
        influence: 5,
    },
    Arcturus: {
        resources: 4,
        influence: 4,
    },
    Acheron: {
        resources: 4,
        influence: 0,
    },
    Elysium: {
        resources: 4,
        influence: 1,
    },
    'The Dark': {
        resources: 3,
        influence: 4,
    },
    Naazir: {
        resources: 2,
        influence: 1,
    },
    Rohka: {
        resources: 1,
        influence: 2,
    },
    Ylir: {
        resources: 0,
        influence: 2,
    },
    Avar: {
        resources: 1,
        influence: 1,
    },
    Valk: {
        resources: 2,
        influence: 0,
    },
    'Archon Vail': {
        resources: 1,
        influence: 3,
        trait: 'hazardous',
    },
    Perimeter: {
        resources: 2,
        influence: 1,
        trait: 'industrial',
    },
    Ang: {
        resources: 2,
        influence: 0,
        trait: 'industrial',
    },
    'Sem-lore': {
        resources: 3,
        influence: 2,
        trait: 'cultural',
    },
    Vorhal: {
        resources: 0,
        influence: 2,
        trait: 'cultural',
    },
    Atlas: {
        resources: 3,
        influence: 1,
        trait: 'hazardous',
    },
    Primor: {
        resources: 2,
        influence: 1,
        trait: 'cultural',
    },
    "Hope's End": {
        resources: 3,
        influence: 0,
        trait: 'hazardous',
    },
    Cormund: {
        resources: 2,
        influence: 0,
        trait: 'hazardous',
    },
    Everra: {
        resources: 3,
        influence: 1,
        trait: 'cultural',
    },
    Accoen: {
        resources: 2,
        influence: 3,
        trait: 'industrial',
    },
    'Jeol Ir': {
        resources: 2,
        influence: 3,
        trait: 'industrial',
    },
    Kraag: {
        resources: 2,
        influence: 1,
        trait: 'hazardous',
    },
    Siig: {
        resources: 0,
        influence: 2,
        trait: 'hazardous',
    },
    "Ba'kal": {
        resources: 3,
        influence: 2,
        trait: 'industrial',
    },
    'Alio Prima': {
        resources: 1,
        influence: 1,
        trait: 'cultural',
    },
    Lisis: {
        resources: 2,
        influence: 2,
        trait: 'industrial',
    },
    Velnor: {
        resources: 2,
        influence: 1,
        trait: 'industrial',
    },
    Cealdri: {
        resources: 0,
        influence: 2,
        trait: 'cultural',
    },
    Xanhact: {
        resources: 0,
        influence: 1,
        trait: 'hazardous',
    },
    'Vega Major': {
        resources: 2,
        influence: 1,
        trait: 'cultural',
    },
    'Vega Minor': {
        resources: 1,
        influence: 2,
        trait: 'cultural',
    },
    Abaddon: {
        resources: 1,
        influence: 0,
        trait: 'cultural',
    },
    Loki: {
        resources: 1,
        influence: 2,
        trait: 'cultural',
    },
    Ashtroth: {
        resources: 2,
        influence: 0,
        trait: 'hazardous',
    },
    'Rigel I': {
        resources: 0,
        influence: 1,
        trait: 'hazardous',
    },
    'Rigel II': {
        resources: 1,
        influence: 2,
        trait: 'hazardous',
    },
    'Rigel III': {
        resources: 1,
        influence: 1,
        trait: 'hazardous',
    },
    Mallice: {
        resources: 0,
        influence: 3,
        trait: 'cultural',
    },
    Mirage: {
        resources: 1,
        influence: 2,
        trait: 'cultural',
    },
    'Custodia Vigilia': {
        resources: 2,
        influence: 3,
    },
    'Etir V': {
        resources: 4,
        influence: 0,
        trait: 'hazardous',
    },
    Echo: {
        resources: 1,
        influence: 2,
        trait: 'hazardous',
    },
    Fakrenn: {
        resources: 2,
        influence: 2,
        trait: 'hazardous',
    },
    Prism: {
        resources: 0,
        influence: 3,
        trait: 'industrial',
    },
    Silence: {
        resources: 2,
        influence: 2,
        trait: 'industrial',
    },
    Tarrock: {
        resources: 3,
        influence: 0,
        trait: 'industrial',
    },
    Troac: {
        resources: 0,
        influence: 4,
        trait: 'cultural',
    },
    Vioss: {
        resources: 3,
        influence: 3,
        trait: 'cultural',
    },
    'San-vit': {
        resources: 3,
        influence: 1,
        trait: 'cultural',
    },
    Lodran: {
        resources: 0,
        influence: 2,
        trait: 'hazardous',
    },
    Dorvok: {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    Derbrae: {
        resources: 2,
        influence: 3,
        trait: 'cultural',
    },
    Moln: {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    Rysaa: {
        resources: 2,
        influence: 0,
        trait: 'hazardous',
    },
    Salin: {
        resources: 1,
        influence: 2,
        trait: 'hazardous',
    },
    Gwiyun: {
        resources: 2,
        influence: 2,
        trait: 'hazardous',
    },
    Inan: {
        resources: 1,
        influence: 2,
        trait: 'industrial',
    },
    Swog: {
        resources: 1,
        influence: 0,
        trait: 'industrial',
    },
    Detic: {
        resources: 3,
        influence: 2,
        trait: 'cultural',
    },
    Lliot: {
        resources: 0,
        influence: 1,
        trait: 'cultural',
    },
    Qaak: {
        resources: 1,
        influence: 1,
        trait: 'cultural',
    },
    Larred: {
        resources: 1,
        influence: 1,
        trait: 'industrial',
    },
    Nairb: {
        resources: 1,
        influence: 1,
        trait: 'hazardous',
    },
    Sierpen: {
        resources: 2,
        influence: 0,
        trait: 'cultural',
    },
    Mandle: {
        resources: 1,
        influence: 1,
        trait: 'industrial',
    },
    Regnem: {
        resources: 0,
        influence: 2,
        trait: 'hazardous',
    },
    Domna: {
        resources: 2,
        influence: 1,
        trait: 'hazardous',
    },
    Rhune: {
        resources: 3,
        influence: 4,
    },
    Kroll: {
        resources: 1,
        influence: 1,
    },
    Cyrra: {
        resources: 0,
        influence: 1,
    },
    Idyn: {
        resources: 1,
        influence: 0,
    },
    Pax: {
        resources: 1,
        influence: 2,
    },
    Kyr: {
        resources: 2,
        influence: 0,
    },
    Vess: {
        resources: 0,
        influence: 1,
    },
    Ogdun: {
        resources: 2,
        influence: 0,
    },
    Brthkul: {
        resources: 1,
        influence: 3,
    },
    Drah: {
        resources: 1,
        influence: 2,
    },
    Trykk: {
        resources: 2,
        influence: 1,
    },
    Vadarian: {
        resources: 3,
        influence: 0,
    },
    Norvus: {
        resources: 1,
        influence: 2,
    },
    Biaheo: {
        resources: 3,
        influence: 0,
    },
    Empero: {
        resources: 0,
        influence: 3,
    },
    Demis: {
        resources: 2,
        influence: 2,
    },
    Chrion: {
        resources: 2,
        influence: 3,
    },
    Axis: {
        resources: 5,
        influence: 0,
    },
    Sanctuary: {
        resources: 3,
        influence: 4,
    },
    'Shi-Halaum': {
        resources: 4,
        influence: 0,
    },
    Discordia: {
        resources: 4,
        influence: 1,
    },
    Cymiae: {
        resources: 3,
        influence: 1,
    },
    Prind: {
        resources: 3,
        influence: 3,
    },
    Gen: {
        resources: 2,
        influence: 0,
    },
    Zelian: {
        resources: 3,
        influence: 3,
    },
    Vaylar: {
        resources: 3,
        influence: 2,
    },
    Delmor: {
        resources: 2,
        influence: 1,
    },
    Kyd: {
        resources: 1,
        influence: 2,
    },
    Abyssus: {
        resources: 4,
        influence: 2,
    },
    Louk: {
        resources: 2,
        influence: 1,
    },
    Auldane: {
        resources: 1,
        influence: 3,
    },
    Ellas: {
        resources: 3,
        influence: 3,
    },
    Aldra: {
        resources: 2,
        influence: 3,
    },
    Beata: {
        resources: 2,
        influence: 1,
    },
    'Bohl-Dhur': {
        resources: 3,
        influence: 4,
    },
    Susuros: {
        resources: 4,
        influence: 4,
    },
    Poh: {
        resources: 2,
        influence: 0,
    },
    Orad: {
        resources: 3,
        influence: 1,
    },
    Kjalengard: {
        resources: 3,
        influence: 2,
    },
    Hulgade: {
        resources: 1,
        influence: 0,
    },
    Benc: {
        resources: 2,
        influence: 0,
    },
    Hau: {
        resources: 1,
        influence: 2,
    },
    Zarr: {
        resources: 2,
        influence: 1,
    },
    Nokk: {
        resources: 1,
        influence: 1,
    },
    'Last Stop': {
        resources: 3,
        influence: 0,
    },
    "Aysis' Rest": {
        resources: 4,
        influence: 3,
    },
    Solitude: {
        resources: 0,
        influence: 1,
    },
    Avicenna: {
        resources: 4,
        influence: 0,
    },
    Alesna: {
        resources: 2,
        influence: 0,
    },
    Azle: {
        resources: 2,
        influence: 0,
    },
    Arche: {
        resources: 2,
        influence: 2,
    },
    'Gghurn Theta': {
        resources: 2,
        influence: 1,
    },
    Ekko: {
        resources: 0,
        influence: 1,
    },
    Edyn: {
        resources: 3,
        influence: 3,
    },
    Okke: {
        resources: 0,
        influence: 1,
    },
    Ghoti: {
        resources: 3,
        influence: 3,
    },
};

export {
    PlanetMeta,
    PlanetName,
    planetNames,
    planets,
    PlanetTrait,
    ResourcesAndInfluence,
};
